/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * 演劇集団すいげつ 予約システム API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorResponse } from './errorResponse';

/**
 * 入力値不正
 */
export type InvalidParameterErrorResponse = ErrorResponse;
