/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * 演劇集団すいげつ 予約システム API
 * OpenAPI spec version: 1.0.0
 */
import type { ReserveInput } from './reserveInput';

export interface PostReservationRequest {
  reservation: ReserveInput;
  turnstileToken: string;
}
