/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 演劇集団すいげつ 予約システム API
 * OpenAPI spec version: 1.0.0
 */

export interface ReserveStatus {
  reserveId?: string;
  label?: string;
  remainCount?: number;
}
