/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 演劇集団すいげつ 予約システム API
 * OpenAPI spec version: 1.0.0
 */
import type { ReserveInputReserveFrom } from './reserveInputReserveFrom';

export interface ReserveInput {
  reserveId: string;
  name: string;
  count: number;
  reserveFrom: ReserveInputReserveFrom;
}
