/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * 演劇集団すいげつ 予約システム API
 * OpenAPI spec version: 1.0.0
 */

export interface ReserveInput {
  name: string;
  email: string;
  reserveId: string;
  count: number;
  findFrom: string[];
  note?: string;
  age: string;
}
