/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * 演劇集団すいげつ 予約システム API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InvalidParameterErrorResponse,
  MaintenanceErrorResponse,
  MaxReserveErrorResponse,
  PostReservationRequest,
  RegistrationClosedErrorResponse,
  RegistrationNotStartedErrorResponse,
  ReserveStatus
} from '../model';

import { customInstance } from '.././customInstance';
import type { ErrorType } from '.././customInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary 予約状況取得API
 */
export const getExec = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReserveStatus[]>(
      {url: `/exec`, method: 'GET', signal
    },
      options);
    }




export const getGetExecQueryKey = () => {
    return [
    `/exec`
    ] as const;
    }


export const getGetExecQueryOptions = <TData = Awaited<ReturnType<typeof getExec>>, TError = ErrorType<RegistrationNotStartedErrorResponse | RegistrationClosedErrorResponse | MaintenanceErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExec>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExecQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExec>>> = ({ signal }) => getExec(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExec>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExecQueryResult = NonNullable<Awaited<ReturnType<typeof getExec>>>
export type GetExecQueryError = ErrorType<RegistrationNotStartedErrorResponse | RegistrationClosedErrorResponse | MaintenanceErrorResponse>


export function useGetExec<TData = Awaited<ReturnType<typeof getExec>>, TError = ErrorType<RegistrationNotStartedErrorResponse | RegistrationClosedErrorResponse | MaintenanceErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExec>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExec>>,
          TError,
          Awaited<ReturnType<typeof getExec>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExec<TData = Awaited<ReturnType<typeof getExec>>, TError = ErrorType<RegistrationNotStartedErrorResponse | RegistrationClosedErrorResponse | MaintenanceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExec>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExec>>,
          TError,
          Awaited<ReturnType<typeof getExec>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExec<TData = Awaited<ReturnType<typeof getExec>>, TError = ErrorType<RegistrationNotStartedErrorResponse | RegistrationClosedErrorResponse | MaintenanceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExec>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 予約状況取得API
 */

export function useGetExec<TData = Awaited<ReturnType<typeof getExec>>, TError = ErrorType<RegistrationNotStartedErrorResponse | RegistrationClosedErrorResponse | MaintenanceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExec>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExecQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary 予約API
 */
export const postExec = (
    postReservationRequest: PostReservationRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/exec`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postReservationRequest, signal
    },
      options);
    }



export const getPostExecMutationOptions = <TError = ErrorType<InvalidParameterErrorResponse | MaxReserveErrorResponse | MaintenanceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postExec>>, TError,{data: PostReservationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postExec>>, TError,{data: PostReservationRequest}, TContext> => {

const mutationKey = ['postExec'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postExec>>, {data: PostReservationRequest}> = (props) => {
          const {data} = props ?? {};

          return  postExec(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostExecMutationResult = NonNullable<Awaited<ReturnType<typeof postExec>>>
    export type PostExecMutationBody = PostReservationRequest
    export type PostExecMutationError = ErrorType<InvalidParameterErrorResponse | MaxReserveErrorResponse | MaintenanceErrorResponse>

    /**
 * @summary 予約API
 */
export const usePostExec = <TError = ErrorType<InvalidParameterErrorResponse | MaxReserveErrorResponse | MaintenanceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postExec>>, TError,{data: PostReservationRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postExec>>,
        TError,
        {data: PostReservationRequest},
        TContext
      > => {
      return useMutation(getPostExecMutationOptions(options), queryClient);
    }
