/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 演劇集団すいげつ 予約システム API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  InvalidParameterErrorResponse,
  MaintenanceErrorResponse,
  MaxReserveErrorResponse,
  RegistrationClosedErrorResponse,
  RegistrationNotStartedErrorResponse,
  ReserveInput,
  ReserveStatus
} from '../model';

import { customInstance } from '.././customInstance';
import type { ErrorType } from '.././customInstance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary 予約状況取得API
 */
export const getReserve = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ReserveStatus[]>(
      {url: `/reserve`, method: 'GET', signal
    },
      options);
    }




export const getGetReserveQueryKey = () => {
    return [
    `/reserve`
    ] as const;
    }


export const getGetReserveQueryOptions = <TData = Awaited<ReturnType<typeof getReserve>>, TError = ErrorType<RegistrationNotStartedErrorResponse | RegistrationClosedErrorResponse | MaintenanceErrorResponse>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReserve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReserveQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReserve>>> = ({ signal }) => getReserve(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReserve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReserveQueryResult = NonNullable<Awaited<ReturnType<typeof getReserve>>>
export type GetReserveQueryError = ErrorType<RegistrationNotStartedErrorResponse | RegistrationClosedErrorResponse | MaintenanceErrorResponse>


export function useGetReserve<TData = Awaited<ReturnType<typeof getReserve>>, TError = ErrorType<RegistrationNotStartedErrorResponse | RegistrationClosedErrorResponse | MaintenanceErrorResponse>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReserve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReserve>>,
          TError,
          Awaited<ReturnType<typeof getReserve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReserve<TData = Awaited<ReturnType<typeof getReserve>>, TError = ErrorType<RegistrationNotStartedErrorResponse | RegistrationClosedErrorResponse | MaintenanceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReserve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReserve>>,
          TError,
          Awaited<ReturnType<typeof getReserve>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReserve<TData = Awaited<ReturnType<typeof getReserve>>, TError = ErrorType<RegistrationNotStartedErrorResponse | RegistrationClosedErrorResponse | MaintenanceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReserve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 予約状況取得API
 */

export function useGetReserve<TData = Awaited<ReturnType<typeof getReserve>>, TError = ErrorType<RegistrationNotStartedErrorResponse | RegistrationClosedErrorResponse | MaintenanceErrorResponse>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReserve>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReserveQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * @summary 予約API
 */
export const postReserve = (
    reserveInput: ReserveInput,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/reserve`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reserveInput, signal
    },
      options);
    }



export const getPostReserveMutationOptions = <TError = ErrorType<InvalidParameterErrorResponse | MaxReserveErrorResponse | MaintenanceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReserve>>, TError,{data: ReserveInput}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postReserve>>, TError,{data: ReserveInput}, TContext> => {

const mutationKey = ['postReserve'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postReserve>>, {data: ReserveInput}> = (props) => {
          const {data} = props ?? {};

          return  postReserve(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostReserveMutationResult = NonNullable<Awaited<ReturnType<typeof postReserve>>>
    export type PostReserveMutationBody = ReserveInput
    export type PostReserveMutationError = ErrorType<InvalidParameterErrorResponse | MaxReserveErrorResponse | MaintenanceErrorResponse>

    /**
 * @summary 予約API
 */
export const usePostReserve = <TError = ErrorType<InvalidParameterErrorResponse | MaxReserveErrorResponse | MaintenanceErrorResponse>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postReserve>>, TError,{data: ReserveInput}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postReserve>>,
        TError,
        {data: ReserveInput},
        TContext
      > => {
      return useMutation(getPostReserveMutationOptions(options), queryClient);
    }
