/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * 演劇集団すいげつ 予約システム API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ReserveStatus
} from '../model';


export const getGetReserveResponseMock = (): ReserveStatus[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({reserveId: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), label: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), remainCount: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined])})))


export const getGetReserveMockHandler = (overrideResponse?: ReserveStatus[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ReserveStatus[]> | ReserveStatus[]), options?: RequestHandlerOptions) => {
  return http.get('*/reserve', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetReserveResponseMock(),
      { status: 200
      })
  }, options)
}

export const getPostReserveMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.post('*/reserve', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}
export const getDefaultMock = () => [
  getGetReserveMockHandler(),
  getPostReserveMockHandler()
]
